apiVersion : apps/v1
kind: Deployment
metadata:
  name: lausiusdockerweather 
spec:
  replicas: __replicaNo__
  selector:
    matchLabels:
      app: lausiusdockerweather
  template:
    metadata:
      labels:
        app: lausiusdockerweather 
    spec:
      containers:
        - name: lausiusdockerweather 
          image: k8sdemoicd.azurecr.io/lausiusdockerweather
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: __environment__
          ports:
          - containerPort: 80